### ISSUE TITLE
Bad network means no map shows up at all.

### ISSUE THREAD

**Issue by karlht** [mozilla-services/location-leaderboard#134] opened 2015-10-13 09:24 UTC
Even hitting reload a couple of times in a row is enough to make the map just give up.  I get the static stuff, but the dynamic content simply doesn't show up.

**Comment by karlht** [comment] 2015-10-14 00:28
This was partially due to Jared making changes to the version I was testing, but not entirely.

**Comment by jaredkerim** [comment] 2016-01-20 21:54
This is essentially not a bug.  If there's poor network connectivity, the site won't work.  On mobile the map is hidden which saves a lot of data transmission.  Also this was produced while testing on a volatile dev environment.  Closing.

**Closed by jaredkerim** 2016-01-20 21:54 UTC
